pubget:
	-cd generated-output/example-openapi/dart-client && flutter pub get
	-cd generated-output/example-openapi/dart-dio-client && flutter pub get
	-cd generated-output/example-openapi/dart-network-client && flutter pub get
	-cd generated-output/example2-openapi/dart-client && flutter pub get
	-cd generated-output/example2-openapi/dart-dio-client && flutter pub get
	-cd generated-output/example2-openapi/dart-network-client && flutter pub get
