//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars


/// Configuration and metadata for the generated API client.
///
/// This class provides access to API metadata extracted from the OpenAPI specification,
/// including base URL, API version, and other useful information.
abstract final class ApiConfig {
  ApiConfig._();

  /// The title of the API.
  static const String apiTitle = 'OpenAPI definition';

  /// The version of the API.
  static const String apiVersion = 'v0';

  /// The description of the API.
  static const String apiDescription = '''No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)''';

  /// Generated server url
  static const String url0_generatedServerUrl = 'https://dummyapi.femrek.dev';

  /// List of all available server URLs.
  static const List<String> serverUrls = [
    url0_generatedServerUrl,
  ];
}
