import 'package:dart_network_layer_core/dart_network_layer_core.dart';
import 'package:dart_network_layer_core/src/request/request_cancel_mixin.dart';
import 'package:dart_network_layer_core/src/request/request_result_mixin.dart';

/// The callback for the progress of the request. Can be used to trace uploading
/// or downloading data.
typedef OnProgressCallback = void Function(int done, int total);

/// The interface/class to configure a request type.
///
/// An implementation should provide the necessary information about the request
/// such as the path, method, payload type, payload data, headers, progress
/// callbacks, etc.
///
/// [T] is the type of the successful response model.
abstract class RequestCommand<T extends Schema>
    with RequestCancelMixin, RequestResultMixin<T> {
  /// The method of the request. GET, POST, PUT, DELETE, etc.
  HttpRequestMethod get method => HttpRequestMethod.get;

  /// The path of the request.
  String get path;

  /// The query parameters of the request.
  List<QueryParameter> get queryParameters => const [];

  /// The headers of the request.
  Map<String, dynamic> get headers => const {};

  /// The payload data of the request. Applicable in the form of Json, form data
  /// or string
  RequestSchema get payload => const EmptyRequestSchema();

  /// The factory instance to deserialize the response.
  SchemaFactory<T> get defaultResponseFactory;

  /// The factory instance to deserialize the error response.
  SchemaFactory get defaultErrorResponseFactory;

  /// The factories for different status codes. This can be used to provide
  /// different response factories for different status codes. For example, if
  /// the server returns a 400 status code, the error response factory can be
  /// different from the one for 500 status code.
  Map<int, SchemaFactory> get responseFactories => const {};

  /// The callback for the progress of the request.
  OnProgressCallback? get onSendProgressUpdate => null;

  /// The callback for the progress of the response.
  OnProgressCallback? get onReceiveProgressUpdate => null;

  /// How to handle binary responses.
  ///
  /// When non-null, the invoker will treat this request as a binary download
  /// rather than a normal JSON/text request.
  ///
  /// Use [InMemoryBinaryResponse] to receive raw bytes in memory, or
  /// [FileBinaryResponse] to save the response to a file at a specified path.
  ///
  /// When null (default), the response is treated as a normal response.
  BinaryResponseType get binaryResponseType => const InMemoryBinaryResponse();

  /// Whether to add header values to string generated by
  /// [RequestCommand.logString]
  bool get logHeaderValues => false;

  /// Whether to add payload values to string generated by
  /// [RequestCommand.logString]
  bool get logRequestPayload => false;

  /// Whether to add query params values to string generated by
  /// [RequestCommand.logString]
  bool get logQueryParamValues => false;

  /// Generates a log string for the request headers.
  String getHeaderLogString(
    Map<String, dynamic> headers, {
    bool? includeValues,
  }) {
    if (headers.isEmpty) return 'none';
    final logValues = includeValues ?? logHeaderValues;
    if (!logValues) return headers.keys.join(', ');

    final buffer = StringBuffer();
    var isFirst = true;
    for (final entry in headers.entries) {
      if (!isFirst) buffer.write(', ');
      buffer
        ..write(entry.key)
        ..write(': ')
        ..write(_obscureValue(entry.key, entry.value));
      isFirst = false;
    }
    return buffer.toString();
  }

  /// Generates a log string for the query parameters.
  String getQueryParameterLogString(
    List<QueryParameter> queryParameters, {
    bool? includeValues,
  }) {
    if (queryParameters.isEmpty) return 'none';
    final logValues = includeValues ?? logQueryParamValues;
    if (!logValues) return queryParameters.map((e) => e.key).join(', ');

    final buffer = StringBuffer();
    var isFirst = true;
    for (final param in queryParameters) {
      if (!isFirst) buffer.write('&');
      buffer
        ..write(param.key)
        ..write('=')
        ..write(_obscureValue(param.key, param.value));
      isFirst = false;
    }
    return buffer.toString();
  }

  /// Generates a log string for the payload.
  String getPayloadLogString(
    RequestSchema payload, {
    bool? includePayload,
  }) {
    if (payload is EmptyRequestSchema) return 'none';
    final logPayload = includePayload ?? logRequestPayload;
    if (!logPayload) return payload.runtimeType.toString();
    return payload.toLogString();
  }

  static final _sensitiveKeyRegex = RegExp(
    'authorization|password|token|secret|cookie|apikey|api_key',
    caseSensitive: false,
  );

  String _obscureValue(String key, dynamic value) {
    if (value != null && _sensitiveKeyRegex.hasMatch(key)) {
      return '***';
    }
    return value?.toString() ?? '';
  }

  /// returns the string representation of the request command, including the
  /// method, path, headers, etc.
  String logString({
    bool includeHeaderValues = false,
    bool includePayload = false,
    bool includeQueryParameterValues = false,
  }) {
    final headerStr = getHeaderLogString(
      headers,
      includeValues: includeHeaderValues,
    );

    final queryStr = getQueryParameterLogString(
      queryParameters,
      includeValues: includeQueryParameterValues,
    );

    final payloadStr = getPayloadLogString(
      payload,
      includePayload: includePayload,
    );
    return '$runtimeType: ${method.name} $path, '
        'Headers: $headerStr, '
        'Query Parameters: $queryStr, '
        'Payload: $payloadStr';
  }
}
