import 'package:dart_network_layer_core/dart_network_layer_core.dart';

/// A mixin that provides logging functionality for HTTP requests.
mixin RequestLoggingMixin {
  /// Whether to add header values to string generated by
  /// [RequestCommand.logString]
  bool get logHeaderValues => false;

  /// Whether to add payload values to string generated by
  /// [RequestCommand.logString]
  bool get logRequestPayload => false;

  /// Whether to add query params values to string generated by
  /// [RequestCommand.logString]
  bool get logQueryParamValues => false;

  /// Generates a log string for the request headers.
  String getHeaderLogString(
    Map<String, dynamic> headers, {
    bool? includeValues,
  }) {
    if (headers.isEmpty) return 'none';
    final logValues = includeValues ?? logHeaderValues;
    if (!logValues) return headers.keys.join(', ');

    final buffer = StringBuffer();
    var isFirst = true;
    for (final entry in headers.entries) {
      if (!isFirst) buffer.write(', ');
      buffer
        ..write(entry.key)
        ..write(': ')
        ..write(_obscureValue(entry.key, entry.value));
      isFirst = false;
    }
    return buffer.toString();
  }

  /// Generates a log string for the query parameters.
  String getQueryParameterLogString(
    List<QueryParameter> queryParameters, {
    bool? includeValues,
  }) {
    if (queryParameters.isEmpty) return 'none';
    final logValues = includeValues ?? logQueryParamValues;
    if (!logValues) return queryParameters.map((e) => e.key).join(', ');

    final buffer = StringBuffer();
    var isFirst = true;
    for (final param in queryParameters) {
      if (!isFirst) buffer.write('&');
      buffer
        ..write(param.key)
        ..write('=')
        ..write(_obscureValue(param.key, param.value));
      isFirst = false;
    }
    return buffer.toString();
  }

  /// Generates a log string for the payload.
  String getPayloadLogString(
    RequestSchema payload, {
    bool? includePayload,
  }) {
    if (payload is EmptyRequestSchema) return 'none';
    final logPayload = includePayload ?? logRequestPayload;
    if (!logPayload) return payload.runtimeType.toString();
    return payload.toLogString();
  }

  static final _sensitiveKeyRegex = RegExp(
    'authorization|password|token|secret|cookie|apikey|api_key',
    caseSensitive: false,
  );

  String _obscureValue(String key, dynamic value) {
    if (value != null && _sensitiveKeyRegex.hasMatch(key)) {
      return '***';
    }
    return value.toString();
  }
}
